version: "3"
services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 4000:4000
    volumes: 
      - ./app
      - '/app/node_modules'
    depends_on: 
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=njsdb
      - MYSQL_USER=theo
      - MYSQL_PASSWORD=0123
      - MYSQL_ROOT_PASSWORD=secret
